services:
  cuccipool:
    build: .
    container_name: cuccipool-app
    ports:
      - "8800:8800"
    volumes:
      - ./actual_results.json:/app/actual_results.json
      - ./leaderboard.json:/app/leaderboard.json
